# Generated by Django 4.0.6 on 2023-01-07 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinators',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cName', models.CharField(max_length=16)),
                ('workPlace', models.CharField(blank=True, max_length=16, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tName', models.CharField(max_length=16)),
                ('profession', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sName', models.CharField(max_length=16)),
                ('age', models.IntegerField(blank=True, default=0, null=True)),
                ('teacherName', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.teacher')),
            ],
        ),
    ]
